/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import Usuarios.ArregloJugadores;
import Usuarios.Buscador;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author alpha
 */
public class Estadisticas extends javax.swing.JFrame {
    
    JLabel[] nikcname, nombre, ganadas, perdidas, jugadas, tiempo;
    private int cantidadJuga;
    private int conta;
    private int posY=75;
    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();        
    }
    
    public void inicilizarArreglos(int cantidadJuga){
        this.cantidadJuga = cantidadJuga;
        nikcname = new JLabel[cantidadJuga]; 
        nombre = new JLabel[cantidadJuga];
        ganadas = new JLabel[cantidadJuga];
        perdidas = new JLabel[cantidadJuga];
        jugadas = new JLabel[cantidadJuga];
        tiempo= new JLabel[cantidadJuga];
        conta=0;
    }
    
    public void PintarArreglo(String lnickname, String lnombre, int lganadas, int lperdidas, int ljugadas, int lhora, int lminuto, int lsegundos){
        nikcname[conta] = new JLabel();
        nombre[conta]= new JLabel();
        ganadas[conta] = new JLabel();
        perdidas[conta] = new JLabel();
        jugadas[conta] = new JLabel();
        tiempo[conta] = new JLabel();
        fondo.add(nikcname[conta]);
        fondo.add(nombre[conta]);
        fondo.add(ganadas[conta]);
        fondo.add(perdidas[conta]);
        fondo.add(jugadas[conta]);
        fondo.add(tiempo[conta]);
        nikcname[conta].setBounds(30, posY, 100, 20);
        nombre[conta].setBounds(135, posY, 100, 20);
        ganadas[conta].setBounds(240, posY, 75, 20);
        perdidas[conta].setBounds(320, posY, 75, 20);
        jugadas[conta].setBounds(400, posY, 75, 20);
        tiempo[conta].setBounds(470, posY, 50, 20);
        nikcname[conta].setText(lnickname);
        nombre[conta].setText(lnombre);
        ganadas[conta].setText(""+lganadas);
        perdidas[conta].setText(""+lperdidas);
        jugadas[conta].setText(""+ljugadas);
        int hora =lhora;
        int minutos= lminuto;
        int segundos= lsegundos;
        String EHora, Eminutos, Esegundos;
        if (segundos<10) {
            Esegundos=":0"+segundos;
        }else {
            Esegundos=":"+segundos;
        }
        if (minutos<10) {
            Eminutos=":0"+minutos;
        }else {
            Eminutos=":"+minutos;
        }
        if (hora<10) {
            EHora=""+hora;
        }else {
            EHora=""+hora;
        }
        tiempo[conta].setText(EHora+Eminutos+Esegundos);
        posY+=25;
        conta++;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        Aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadisticas ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nickname");

        jLabel2.setText("Ganadas");

        jLabel3.setText("Perdidas");

        jLabel4.setText("Jugadas");

        jLabel5.setText("Tiempo");

        jLabel6.setText("Nombre");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Aceptar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_AceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
