/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NuevoJuego;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author alpha
 */
public class Dados extends javax.swing.JPanel implements Runnable {
    private boolean mover=false;
    private JLabel dado1= new JLabel();
    private JLabel dado2= new JLabel();
    /**
     * Creates new form Dados
     */
    public Dados() {
        initComponents();
        
    }
    
    public void setMover(boolean mover){
        this.mover=mover;
    }
    
    public void IniciarDado(int num1, int num2){
        dado1.setBounds(0, 0, 80, 80);
        dado2.setBounds(94, 0, 80, 80);
        this.add(dado1);
        this.add(dado2);
        ImageIcon Imagen1= new ImageIcon("Imagenes/caras"+num1+".jpg");
        Icon Fondo1= new ImageIcon(Imagen1.getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
        dado1.setIcon(Fondo1);
        ImageIcon Imagen2= new ImageIcon("Imagenes/caras"+num2+".jpg");
        Icon Fondo2= new ImageIcon(Imagen2.getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
        dado2.setIcon(Fondo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        while(mover==true){
            int tmp1=(int)(Math.random()*6)+1;
            ImageIcon Imagen1= new ImageIcon("Imagenes/caras"+tmp1+".jpg");
            Icon Fondo1= new ImageIcon(Imagen1.getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            dado1.setIcon(Fondo1);
            int tmp2=(int)(Math.random()*6)+1;
            ImageIcon Imagen2= new ImageIcon("Imagenes/caras"+tmp2+".jpg");
            Icon Fondo2= new ImageIcon(Imagen2.getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            dado2.setIcon(Fondo2);
            try {
                Thread.sleep(200);
            } catch (InterruptedException ex) {
                Logger.getLogger(Dados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
